---
# tasks file for bastion-host-proxycommand
- name: Assert ProxyCommand Attributes
  assert:
    that:
      - target_host_range is defined
      - bastion_host_name is defined
      - protected_private_key is defined
    msg: Missing attributes required to set ProxyCommand

- name: Update SSH Config with ProxyCommand to Bastion Configuration
  blockinfile:
    path: ~/.ssh/config
    create: yes
    backup: yes
    mode: 0600
    block: |
      Host {{ target_host_range }}
        ProxyCommand ssh -W %h:%p {{ bastion_host_name }}
        IdentityFile {{ protected_private_key | default('~/.ssh/id_rsa') }}
