---
# tasks file for bastion-host-proxycommand
- name: Assert ProxyCommand Attributes
  assert:
    that:
      - bastion_target_host_range is defined
      - bastion_host_name is defined
      - bastion_protected_private_key is defined
    msg: Missing attributes required to set ProxyCommand

- name: Update SSH Config with ProxyCommand to Bastion Configuration
  blockinfile:
    path: ~/.ssh/config
    create: yes
    backup: yes
    mode: 0600
    block: |
      Host {{ bastion_target_host_range }}
        ProxyCommand ssh -W %h:%p {{ bastion_host_name }}
        IdentityFile {{ bastion_protected_private_key | default('~/.ssh/id_rsa') }}
#  when: ansible_distribution == 'CentOS'

#- name: Update SSH Config with ProxyCommand to Bastion Configuration for GMac
#  blockinfile:
#    path: ~/.ssh/config
#    create: yes
#    backup: yes
#    mode: 0600
#    block: |
#      Host {{ bastion_target_host_range }}
#        ProxyCommand corp-ssh-helper -W %h:%p {{ bastion_host_name }}
#        IdentityFile {{ bastion_protected_private_key | default('~/.ssh/id_rsa') }}
#  when: ansible_distribution == 'MacOSX'
